{{- if .Values.azureCredentials.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "azure-nodepool-metrics.azureCredentialsSecretName" . }}
  namespace: {{ $.Release.Namespace }}
data:
  {{- toYaml .Values.azureCredentials.data | nindent 2 }}
{{- end }}
