{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "azure-nodepool-metrics.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "azure-nodepool-metrics.labels" . | nindent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "azure-nodepool-metrics.fullname" . }}
  namespace: {{ .Release.Namespace }}
rules:
  - apiGroups: ["*"]
    resources: ["configmaps"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "azure-nodepool-metrics.fullname" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "azure-nodepool-metrics.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "azure-nodepool-metrics.fullname" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
